go get -v github.com/Shopify/sarama
go get -v github.com/hashicorp/go-version
go get -v github.com/onsi/ginkgo
go get -v github.com/onsi/gomega
go get -v github.com/spf13/cobra
go get -v github.com/syndtr/goleveldb/leveldb
go get -v github.com/syndtr/goleveldb/leveldb/iterator
go get -v github.com/syndtr/goleveldb/leveldb/opt
go get -v github.com/syndtr/goleveldb/leveldb/util
go get -v github.com/tedsuo/ifrit
go get -v github.com/willf/bitset
go get -v golang.org/x/sync/semaphore
